version: '3'

services:

  mysql:
      image: mysql:5.7
      container_name: mysql
      volumes:
        - ./DevOps/dumpMySql/dump.sql:/docker-entrypoint-initdb.d/init.sql
      env_file:
        - ./DevOps/.env

  php-myadmin:
      container_name: phpmyadmin
      image: splattael/phpmyadmin
      links:
        - mysql
      ports:
        - 8100:80
      depends_on:
        - "mysql"

  rabbitmq:
      image: bitnami/rabbitmq:3.7
      container_name: rabbitmq
      ports:
        - "5672:5672"
        - "15672:15672"
      env_file:
        - ./DevOps/.env

  hello-node:
      build: ./hello-node
      container_name: hello-node
      restart: always
      depends_on:
        - "rabbitmq"
        - "mysql"
      ports:
        - "3000:3000"
      env_file:
        - ./DevOps/.env

  hello-python:
      build: ./hello-python
      container_name: hello-python
      depends_on:
        - "rabbitmq"
        - "mysql"
      ports:
        - "8000:8000"
      env_file:
        - ./DevOps/.env