
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: result-ingress
  namespace: vote
spec:
  rules:
  - host: result.bardodevops.com.br
    http:
      paths:
      - path: /
        backend:
          serviceName: result
          servicePort: result-service
---
apiVersion: v1
kind: Service
metadata:
  name: result
  namespace: vote
spec:
  type: NodePort
  ports:
  - name: "result-service"
    port: 5001
    targetPort: 80
    nodePort: 31001
  selector:
    app: result
