apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vote
  namespace: vote
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - image: renatoruis/vote-app:0.1
        name: vote
